apiVersion: v1
kind: Pod
metadata:
  name: producer-pod
  namespace: producer  # Specify the namespace for your producer pod
spec:
  containers:
    - name: producer-container
      image: mohitsalgotra/producer-image:1.0.0
      env:
        - name: KAFKA_BOOTSTRAP_SERVER
          value: "kafka-cluster-kafka-bootstrap.default.svc.cluster.local:9092" 
