name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Configure Google Cloud project and install dependencies
        run: |
          gcloud config set project healthy-pager-444306-e9
          gcloud components install gke-gcloud-auth-plugin kubectl -q

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

      - name: Test Kubernetes Connection
        run: kubectl get pods
