name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube # Create the .kube directory if it doesn't exist
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

      - name: Test kubectl connection
        run: kubectl get pods
