name: Test Kubernetes Cluster Access and Deploy Applications

on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed
  workflow_dispatch:

jobs:
  test-cluster-access-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Authenticate with Google Cloud
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_KEY }}

    # Step 3: Set up gcloud CLI
    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: gke-gcloud-auth-plugin

    # Step 4: Decode kubeconfig and set it up
    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    # Step 5: Test Kubernetes cluster access
    - name: Test Kubernetes access
      run: kubectl get nodes

    # Step 6: Deploy Consumer Application
    - name: Deploy Consumer Application
      run: |
        kubectl apply -f k8s/deployment.consum.yaml
      

    # Step 7: Deploy Producer Application
    - name: Deploy Producer Application
      run: |
        kubectl apply -f k8s/deployment.prod.yaml
        
