name: Test Cluster Connection

on:
  push:
    branches:
      - master

jobs:
  test-cluster-connection:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Set up Google Cloud CLI
    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: healthy-pager-444306-e9
        credentials_json: ${{ secrets.GCP_KEY }}

    # Step 2: Decode and configure kubeconfig
    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    # Step 3: Verify connection to cluster
    - name: Test connection
      run: kubectl get nodes
