name: CI Pipeline - Consumer and Producer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-consumer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Consumer Image
      uses: docker/build-push-action@v5
      with:
        context: ./consumer
        push: true
        tags: mohitsalgotra/consumer-image:1.0.0

  build-producer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Producer Image
      uses: docker/build-push-action@v5
      with:
        context: ./producer
        push: true
        tags: mohitsalgotra/producer-image:1.0.0
